export const enum AboutMeIndexTypes {
  'ABOUT_ME' = 'ABOUT_ME',
  'EXPERIENCE' = 'EXPERIENCE',
  'PROJECTS' = 'PROJECTS',
  'PROGRAMING_LANGUAGES' = 'PROGRAMING_LANGUAGES',
  'FRAMEWORKS' = 'FRAMEWORKS',
  'SPEAKING_LANGUAGES' = 'SPEAKING_LANGUAGES',
}
