export const enum SectionsTypes {
  'FIRST_SECTIONS' = 'FIRST_SECTIONS',
  'SECOND_SECTIONS' = 'SECONDSECTIONS',
  'THIRD_SECTIONS' = 'THIRDSECTIONS',
  'FOURTH_SECTIONS' = 'FOURTH_SECTIONS',
  'NONE' = 'NONE',
}
