export const IntroWords = [
  'ambitious',
  'creative',
  'hard working',
  'motivated',
  'experienced',
  'flexible',
  'innovative',
  'organised',
  'reliable',
  'team player',
  'passionate',
  'ambitious',
  'creative',
  'hard working',
  'motivated',
  'experienced',
  'flexible',
  'innovative',
  'organised',
  'reliable',
  'team player',
  'passionate',
  'ambitious',
  'creative',
  'hard working',
  'motivated',
  'experienced',
  'flexible',
  'innovative',
  'organised',
  'reliable',
  'team player',
  'passionate',
  'ambitious',
  'creative',
  'hard working',
  'motivated',
  'experienced',
  'flexible',
  'innovative',
  'organised',
  'reliable',
  'team player',
  'passionate',
  'ambitious',
  'creative',
  'hard working',
  'motivated',
  'experienced',
  'flexible',
  'innovative',
  'organised',
  'reliable',
  'team player',
  'passionate',
  'ambitious',
  'creative',
  'hard working',
  'motivated',
  'experienced',
  'flexible',
  'innovative',
  'organised',
  'reliable',
  'team player',
  'passionate',
]
